spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc_demo
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  
springdoc:
  api-docs:
    enabled: true
    
    
